# Generated by Django 4.2 on 2024-10-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_created_product_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
