# Generated by Django 4.2 on 2024-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='contact',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='portfolio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='testimoni',
            field=models.CharField(max_length=266, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='work_experience',
            field=models.CharField(max_length=888, null=True),
        ),
    ]
